"""Section 8: retrieve using a hypothetical answer generated by the LLM."""

from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.runnables import RunnableLambda

from rag_tutorial.shared import (
    build_blog_resources,
    create_base_rag_prompt,
    create_llm,
    format_docs,
)

HYDE_TEMPLATE = """Write a short hypothetical document passage that would
answer the question. The passage is used only for semantic retrieval.

Question: {question}

Hypothetical passage:"""


def build_hyde_rag_chain():
    resources = build_blog_resources("section_08_hyde")
    llm = create_llm()
    generate_hypothetical_document = (
        ChatPromptTemplate.from_template(HYDE_TEMPLATE)
        | llm
        | StrOutputParser()
    )

    def retrieve(input_data: dict):
        hypothetical_document = generate_hypothetical_document.invoke(input_data)
        print("HyDE hypothetical document:")
        print(hypothetical_document)
        return resources.retriever.invoke(hypothetical_document)

    return (
        {
            "context": RunnableLambda(retrieve) | format_docs,
            "question": RunnableLambda(lambda data: data["question"]),
        }
        | create_base_rag_prompt()
        | llm
        | StrOutputParser()
    )


def main() -> None:
    chain = build_hyde_rag_chain()
    print(chain.invoke({"question": "What is task decomposition for LLM agents?"}))


if __name__ == "__main__":
    main()

